[0.000000] (-) TimerEvent: {}
[0.002071] (py_pubsub) JobQueued: {'identifier': 'py_pubsub', 'dependencies': OrderedDict()}
[0.002988] (py_pubsub) JobStarted: {'identifier': 'py_pubsub'}
[0.103228] (-) TimerEvent: {}
[0.204102] (-) TimerEvent: {}
[0.305638] (-) TimerEvent: {}
[0.406857] (-) TimerEvent: {}
[0.508014] (-) TimerEvent: {}
[0.608786] (-) TimerEvent: {}
[0.709488] (-) TimerEvent: {}
[0.810185] (-) TimerEvent: {}
[0.910857] (-) TimerEvent: {}
[1.011525] (-) TimerEvent: {}
[1.112463] (-) TimerEvent: {}
[1.213168] (-) TimerEvent: {}
[1.313862] (-) TimerEvent: {}
[1.414538] (-) TimerEvent: {}
[1.515260] (-) TimerEvent: {}
[1.616619] (-) TimerEvent: {}
[1.718603] (-) TimerEvent: {}
[1.820428] (-) TimerEvent: {}
[1.922348] (-) TimerEvent: {}
[2.023550] (-) TimerEvent: {}
[2.124319] (-) TimerEvent: {}
[2.225164] (-) TimerEvent: {}
[2.283559] (py_pubsub) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 51, in build\n    setup_py_data = get_setup_data(self.context.pkg, env)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/__init__.py", line 20, in get_setup_data\n    return dict(pkg.metadata[key](env))\n  File "/usr/lib/python3/dist-packages/colcon_ros/package_augmentation/ros_ament_python.py", line 57, in getter\n    return get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 241, in get_setup_information\n    _setup_information_cache[hashable_env] = _get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 288, in _get_setup_information\n    result = subprocess.run(\n  File "/usr/lib/python3.10/subprocess.py", line 526, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/python3\', \'-c\', \'import sys;from contextlib import suppress;exec("with suppress(ImportError):    from setuptools.extern.packaging.specifiers    import SpecifierSet");exec("with suppress(ImportError):    from packaging.specifiers import SpecifierSet");from distutils.core import run_setup;dist = run_setup(    \\\'setup.py\\\', script_args=(\\\'--dry-run\\\',), stop_after=\\\'config\\\');skip_keys = (\\\'cmdclass\\\', \\\'distclass\\\', \\\'ext_modules\\\', \\\'metadata\\\');data = {    key: value for key, value in dist.__dict__.items()     if (        not key.startswith(\\\'_\\\') and         not callable(value) and         key not in skip_keys and         key not in dist.display_option_names    )};data[\\\'metadata\\\'] = {    k: v for k, v in dist.metadata.__dict__.items()     if k not in (\\\'license_files\\\', \\\'provides_extras\\\')};sys.stdout.buffer.write(repr(data).encode(\\\'utf-8\\\'))\']\' returned non-zero exit status 1.\n'}
[2.285703] (py_pubsub) JobEnded: {'identifier': 'py_pubsub', 'rc': 1}
[2.295819] (-) EventReactorShutdown: {}
